### ISSUE TITLE
Particles reset on click

### ISSUE THREAD

**Issue by JanGross** [kurzgesagt-life/kurzgesagt-life.github.io#3]
https://github.com/kurzgesagt-life/kurzgesagt-life.github.io/blob/ba1a6aab031187b12aed072453f7b140b4d8eb62/script.js#L100

Why are we resetting the particles on click?  
Makes clicking feel like something should have happened but it didn't work.

**Comment by Bryzizzle** [comment]
I think someone talked about this in the discord early-on, I think it was actually a feature. But I'm really not sure.

**Comment by Toby56** [comment]
This is probably because the background is originally more of a codepen experiment style thing. I am actually working on improving the website overall (including the header background animation). I've been busy lately, but I want to make it into a simple page where we can showcase progress/screenshots/features for the game later, if anyone else thinks that would be a good idea

**Comment by JanGross** [comment]
Closing this issue as it will no longer be relevant for the reworked site.
